[build]
  command = "cd app && npm run build && cd ../widget && npm run build && cp dist/widget.js ../app/dist/widget.js"
  publish = "app/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
